name: Do a random amount of Duolingo lessons

on:
    workflow_dispatch:
        inputs:
            times:
                default: 1
                description: 'Number of times this script will be run'
                required: false
                type: number

jobs:
    random:
        runs-on: ubuntu-latest
        steps:
            - run: echo "random=$( shuf -i 1-999 -n 1 )" >> $GITHUB_ENV

            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - run: node index.js
              env:
                DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
                LESSONS: ${{ env.random }}
        