name: Do a random amount of Duolingo lessons

on:
    workflow_dispatch:
        inputs:
            minimum:
                default: 1
                description: 'The minimum number of lessons to be completed'
                required: false
                type: number
            maximum:
                default: 1
                description: 'The maximum number of lessons to be completed'
                required: false
                type: number

jobs:
    random:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10' 

            - run: python
            - run: random.randrange(${{ inputs.minimum }}, ${{ inputs.maximum }})