name: Do a random amount of Duolingo lessons

on:
    workflow_dispatch:
        inputs:
            minimum:
                default: 1
                description: 'The minimum number of lessons to be completed'
                required: false
                type: number
            maximum:
                default: 1
                description: 'The maximum number of lessons to be completed'
                required: false
                type: number

jobs:
    random:
        runs-on: ubuntu-latest
        steps:
            # - run: shuf -i ${{ inputs.minimum }}-${{ inputs.maximum }} -n 1
            # - run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV
            - run: echo "RANDOM=$( shuf -i ${{ inputs.minimum }}-${{ inputs.maximum }} -n 1 )" >> $GITHUB_ENV

            - run: echo ${{ env.RANDOM }}